baseURL: https://thealoneman.com
locale: en-us
title: The Alone Man
#theme: hextra
copyright: "Richard A. Sand. All rights reserved."

module:
  imports:
    - path: github.com/imfing/hextra

params:
  contact:
    email: richard@richardsand.com
    phone: +1 267-984-3651
  footer:
    displayCopyright: true
    displayPoweredBy: false
  copyright: "Richard A. Sand. All rights reserved."
  navbar:
    displayLogo: false
    displayTitle: true

menus:
  main:
    - name: Characters
      identifier: characters
      weight: 20

    - name: "(All)"
      pageRef: /characters
      parent: characters
      weight: 1

    - name: Dr. David Kahn
      pageRef: /characters/david-kahn
      parent: characters
      weight: 10

    - name: Kathleen Tiggs, Lieutenant
      pageRef: /characters/kathleen-tiggs
      parent: characters
      weight: 20

    - name: Ray Teller, Corporal
      pageRef: /characters/ray-teller
      parent: characters
      weight: 30

    - name: Dr. Aaron Cohen, Captain
      pageRef: /characters/aaron-cohen
      parent: characters
      weight: 40

    - name: Colonel Bryce
      pageRef: /characters/col-bryce
      parent: characters
      weight: 50

    - name: History
      identifier: history
      weight: 30

    - name: 121st Evac Hospital
      pageRef: /history/121st
      parent: history
      weight: 1

    - name: Author
      pageRef: /about
      weight: 40

    - name: Contact
      pageRef: /contact
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true